"use client";
import { FormEvent, useState } from "react";
type State={generation:number;version:number;digest:string;scenarios:{id:string;title:string;risk:string}[]};
export default function SyntheticControlPage(){
 const [state,setState]=useState<State|null>(null);const [scenario,setScenario]=useState("");const [confirmation,setConfirmation]=useState("");const [message,setMessage]=useState("Load state to begin.");
 async function load(){const r=await fetch("/api/v1/synthetic-control",{cache:"no-store"});if(!r.ok){setMessage("Control state is unavailable.");return;}const value=await r.json() as State;setState(value);setScenario(value.scenarios[0]?.id??"");setMessage("Synthetic baseline loaded.");}
 async function mutate(path:string,body:object){const r=await fetch(`/api/v1/synthetic-control/${path}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});if(!r.ok){setMessage("Action was denied or conflicted. Reload state.");return;}setMessage("Action completed and recorded.");await load();}
 function activate(e:FormEvent){e.preventDefault();if(state)void mutate("activate",{scenario_id:scenario,expected_version:state.version});}
 return <main id="main-content" className="shell"><p className="eyebrow">Synthetic demo only</p><h1>Environment control</h1><p>This panel cannot connect to production endpoints.</p><section className="panel" aria-live="polite"><button onClick={()=>void load()}>Load current state</button><p>{message}</p>{state&&<><dl><dt>Generation</dt><dd>{state.generation}</dd><dt>Version</dt><dd>{state.version}</dd><dt>State digest</dt><dd><code>{state.digest}</code></dd></dl><form onSubmit={activate}><label htmlFor="scenario">Controlled scenario</label><select id="scenario" value={scenario} onChange={e=>setScenario(e.target.value)}>{state.scenarios.map(s=><option key={s.id} value={s.id}>{s.title} ({s.risk})</option>)}</select><button type="submit">Preview and activate</button></form><button onClick={()=>void mutate("rollback",{expected_version:state.version})}>Rollback last change</button><form onSubmit={e=>{e.preventDefault();void mutate("reset",{confirmation});}}><label htmlFor="confirmation">Type RESET SYNTHETIC TENANT</label><input id="confirmation" value={confirmation} onChange={e=>setConfirmation(e.target.value)}/><button disabled={confirmation!=="RESET SYNTHETIC TENANT"} type="submit">Reset environment</button></form></>}</section></main>;
}
