"use client";
import {FormEvent,useEffect,useMemo,useReducer,useRef,useState} from "react";
import type {SafeRuntimeEvent,TimelineItem,WorkspaceMode,WorkspaceState} from "./workspace-types";
const INITIAL:WorkspaceState={mode:"synthetic",connection:"offline",incidentId:"INC-DEMO-1042",status:"Awaiting diagnostics",route:"Windows and network specialist",lastCursor:3,progress:35,timeline:[
 {cursor:1,eventId:"demo-1",kind:"graph",title:"Incident received",summary:"The employee reports Outlook is disconnected on a registered Windows 11 laptop.",status:"complete",occurredAt:"10:02",evidenceCount:0},
 {cursor:2,eventId:"demo-2",kind:"graph",title:"Device confirmed",summary:"The employee confirmed the minimally disclosed registered device.",status:"complete",occurredAt:"10:03",evidenceCount:1},
 {cursor:3,eventId:"demo-3",kind:"interrupt",title:"Diagnostic consent required",summary:"Read-only network and Outlook checks are waiting for employee consent.",status:"waiting",occurredAt:"10:04",evidenceCount:1}],
 evidence:[{id:"EV-1042-01",kind:"asset_relationship",summary:"Confirmed device relationship",source:"Asset registry",observedAt:"10:03",freshness:"current"}],
 interrupt:{id:"INT-1042-01",kind:"diagnostic_consent",title:"Allow read-only diagnostics?",summary:"DeskPilot will inspect connection, Outlook status and relevant Windows services. It will not read email content or change settings.",risk:"read_only",expiresAt:"10:19",checkpointId:"CP-3",actionIds:["network.status.read","outlook.connectivity.read"],evidenceIds:["EV-1042-01"],rollbackAvailable:false}};
type Action={type:"connection";value:WorkspaceState["connection"]}|{type:"event";value:SafeRuntimeEvent}|{type:"decision";value:string}|{type:"mode";value:WorkspaceMode};
const ALLOWED_FIELDS=new Set(["phase","status","agent_id","route_reason","interrupt_kind","decision_required","evidence_count","error_class","recovery_route","trace_head_sha256"]);
const EVENT_TITLES:Record<SafeRuntimeEvent["event_type"],string>={graph:"Support journey updated",interrupt:"Your decision is required",decision:"Decision recorded",terminal:"Support journey completed",error:"Support update unavailable"};
function reducer(state:WorkspaceState,action:Action):WorkspaceState{if(action.type==="connection")return{...state,connection:action.value};if(action.type==="mode")return{...INITIAL,mode:action.value,connection:"offline"};if(action.type==="decision")return{...state,interrupt:null,status:action.value,progress:48};const event=action.value;if(event.cursor<=state.lastCursor||Object.keys(event.fields).some(key=>!ALLOWED_FIELDS.has(key)))return state;const item:TimelineItem={cursor:event.cursor,eventId:event.event_id,kind:event.event_type,title:EVENT_TITLES[event.event_type],summary:String(event.fields.route_reason??event.fields.status??"Agent state updated."),status:String(event.fields.status??state.status),occurredAt:new Date().toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"}),evidenceCount:Number(event.fields.evidence_count??0)};return{...state,lastCursor:event.cursor,status:item.status,timeline:[...state.timeline,item].slice(-100),progress:Math.min(100,state.progress+8)}}
export default function IncidentWorkspacePage(){const[state,dispatch]=useReducer(reducer,INITIAL);const[decisionReason,setDecisionReason]=useState("");const source=useRef<EventSource|null>(null);useEffect(()=>()=>source.current?.close(),[]);
 function connect(){source.current?.close();dispatch({type:"connection",value:state.lastCursor?"reconnecting":"connecting"});const stream=new EventSource(`/api/v1/agent-runs/${encodeURIComponent(state.incidentId)}/events?after_cursor=${state.lastCursor}&mode=${state.mode}`);source.current=stream;stream.onopen=()=>dispatch({type:"connection",value:"connected"});stream.onmessage=message=>{try{dispatch({type:"event",value:JSON.parse(message.data) as SafeRuntimeEvent})}catch{dispatch({type:"connection",value:"reconnecting"})}};stream.onerror=()=>dispatch({type:"connection",value:"reconnecting"})}
 function submitDecision(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!state.interrupt)return;dispatch({type:"decision",value:decisionReason==="decline"?"Consent declined":"Decision recorded"});setDecisionReason("")}
 const completed=useMemo(()=>state.timeline.filter(item=>item.status==="complete").length,[state.timeline]);
 return <main id="main-content" className="shell"><header className="workspace-header"><div><p className="eyebrow">Incident workspace</p><h1>Support journey</h1><p className="muted">{state.incidentId} · Windows 10/11 private support</p></div><span className={`mode-badge ${state.mode}`}>{state.mode==="synthetic"?"Synthetic demonstration":"Live authorized environment"}</span></header>
 <section className="panel" aria-label="Workspace controls"><div className="panel-heading"><div><span className="status-pill">{state.status}</span><p className="muted">Current route: {state.route}</p></div><span role="status" className={`connection ${state.connection==="reconnecting"?"reconnecting":""}`}>{state.connection}</span></div><label htmlFor="mode">Environment boundary</label><select id="mode" value={state.mode} onChange={event=>dispatch({type:"mode",value:event.target.value as WorkspaceMode})}><option value="synthetic">Synthetic recruiter demonstration</option><option value="live">Live authorized tenant</option></select><p className="muted">Changing environment clears local state. Synthetic mode cannot contact managed endpoints.</p><button type="button" onClick={connect}>{state.lastCursor?"Reconnect from cursor":"Connect timeline"}</button></section>
 <div className="workspace-grid"><div className="column"><section className="panel" aria-labelledby="timeline-heading"><div className="panel-heading"><h2 id="timeline-heading">Live agent timeline</h2><span className="muted">Cursor {state.lastCursor}</span></div><div className="progress" aria-label={`${state.progress}% support journey complete`}><span style={{width:`${state.progress}%`}}/></div><ol className="timeline" aria-live="polite">{state.timeline.map(item=><li key={item.eventId}><strong>{item.title}</strong><p>{item.summary}</p><div className="timeline-meta"><span>{item.occurredAt}</span><span>{item.evidenceCount} evidence</span></div></li>)}</ol></section><section className="panel" aria-labelledby="evidence-heading"><div className="panel-heading"><h2 id="evidence-heading">Evidence</h2><span className="muted">References only</span></div><ul className="evidence-list">{state.evidence.map(item=><li key={item.id}><strong>{item.summary}</strong><p className="muted">{item.id} · {item.source} · {item.observedAt}</p></li>)}</ul></section></div>
 <aside className="column" aria-label="Incident controls"><section className="panel"><h2>Journey status</h2><div className="stat-grid"><div className="stat"><strong>{completed}</strong><span>completed</span></div><div className="stat"><strong>{state.evidence.length}</strong><span>evidence</span></div><div className="stat"><strong>{state.interrupt?1:0}</strong><span>waiting</span></div></div></section>
 {state.interrupt?<section className="panel interrupt-card" aria-labelledby="interrupt-heading"><p className="eyebrow">Human decision required</p><h2 id="interrupt-heading">{state.interrupt.title}</h2><p>{state.interrupt.summary}</p><dl><dt>Scope</dt><dd>{state.interrupt.actionIds.join(", ")}</dd><dt>Expires</dt><dd>{state.interrupt.expiresAt}</dd><dt>Risk</dt><dd>{state.interrupt.risk}</dd></dl><form onSubmit={submitDecision}><fieldset><legend>Your decision</legend><label><input type="radio" name="decision" value="approve" checked={decisionReason==="approve"} onChange={event=>setDecisionReason(event.target.value)}/> Allow scoped checks</label><label><input type="radio" name="decision" value="decline" checked={decisionReason==="decline"} onChange={event=>setDecisionReason(event.target.value)}/> Decline and stop</label></fieldset><button disabled={!decisionReason} type="submit">Confirm decision</button></form></section>:<section className="panel"><h2>No decision waiting</h2><p className="muted">The journey continues only through governed graph transitions.</p></section>}
 <section className="panel"><h2>Safety boundaries</h2><ul className="action-list"><li>No passwords or email content</li><li>No change without approval</li><li>Rollback before closure</li><li>Employee confirms the outcome</li></ul></section></aside></div></main>}
