"use client";
import { FormEvent,useState } from "react";
type Pack={pack_id:string;title:string;theme:string;estimated_minutes:number};type Step={id:string;title:string;narration:string;checkpoint:string};type DemoState={state:"ready"|"running"|"completed";generation:number;pack:{title:string;steps:Step[]}|null;current_step:Step|null;step_index:number;synthetic_only:true};
export default function GuidedDemoPage(){const [packs,setPacks]=useState<Pack[]>([]);const [selected,setSelected]=useState("");const [state,setState]=useState<DemoState|null>(null);const [message,setMessage]=useState("Load curated packs to begin.");
 async function request(path:string,body?:object){const r=await fetch(`/api/v1/guided-demo${path}`,{method:body?"POST":"GET",headers:body?{"content-type":"application/json"}:undefined,body:body?JSON.stringify(body):undefined});if(!r.ok){setMessage("The guided action was denied or unavailable.");return null;}return r.json();}
 async function load(){const value=await request("");if(value){setPacks(value.packs);setSelected(value.packs[0]?.pack_id??"");setMessage("Curated synthetic packs loaded.");}}
 async function start(e:FormEvent){e.preventDefault();const value=await request("/start",{pack_id:selected});if(value){setState(value);setMessage("Guided replay started.");}}
 async function advance(){const value=await request("/advance",{});if(value){setState(value);setMessage(value.state==="completed"?"Guided replay completed.":"Advanced one governed step.");}}
 async function reset(){const value=await request("/reset",{confirmation:"RESET GUIDED DEMO"});if(value){setState(value);setMessage("Demo reset to its deterministic ready state.");}}
 return <main id="main-content" className="shell"><p className="eyebrow">Synthetic demo only</p><h1>Guided recruiter demonstration</h1><p>No production endpoint can be contacted from this mode.</p><section className="panel" aria-live="polite"><button onClick={()=>void load()}>Load curated packs</button><p>{message}</p>{packs.length>0&&<form onSubmit={start}><label htmlFor="pack">Demonstration pack</label><select id="pack" value={selected} onChange={e=>setSelected(e.target.value)}>{packs.map(p=><option value={p.pack_id} key={p.pack_id}>{p.title} · {p.estimated_minutes} min</option>)}</select><button type="submit">Start guided replay</button></form>}{state?.pack&&<><h2>{state.pack.title}</h2><p>Step {state.step_index+1} of {state.pack.steps.length}</p><h3>{state.current_step?.title}</h3><p>{state.current_step?.narration}</p><p><strong>Checkpoint:</strong> {state.current_step?.checkpoint}</p><button disabled={state.state==="completed"} onClick={()=>void advance()}>Next governed step</button><button onClick={()=>void reset()}>Reset guided demo</button></>}</section></main>}
