from __future__ import annotations

from .models import DemoScenario, ScenarioExpectation


GOLDEN_DEMO_SCENARIOS: tuple[DemoScenario, ...] = (
    DemoScenario(
        "DEMO-PRINTER-QUEUE",
        "Printer queue stuck",
        "printer",
        "demo-printer-001",
        "tenant-a",
        "WIN11-PC-001",
        "Printer jobs are stuck in the spooler queue and nothing prints.",
        "restart_spooler",
        ScenarioExpectation.CLOSED,
        expected_injection_block=True,
    ),
    DemoScenario(
        "DEMO-PRINTER-OFFLINE",
        "Printer offline",
        "printer",
        "demo-printer-002",
        "tenant-a",
        "WIN11-PC-002",
        "The network printer shows offline and users cannot print.",
        "refresh_printer_connection",
        ScenarioExpectation.CLOSED,
        expected_injection_block=True,
    ),
    DemoScenario(
        "DEMO-OUTLOOK-DISCONNECTED",
        "Outlook disconnected",
        "outlook",
        "demo-outlook-001",
        "tenant-a",
        "WIN11-PC-003",
        "Outlook shows Disconnected and mailbox synchronization has stopped.",
        "refresh_outlook_sync",
        ScenarioExpectation.CLOSED,
        expected_injection_block=True,
    ),
    DemoScenario(
        "DEMO-OUTLOOK-CRASH",
        "Outlook crashes",
        "outlook",
        "demo-outlook-002",
        "tenant-a",
        "WIN11-PC-004",
        "Outlook crashes shortly after launch and an add-in is suspected.",
        "restart_outlook",
        ScenarioExpectation.CLOSED,
        expected_injection_block=True,
    ),
    DemoScenario(
        "DEMO-VERIFY-FAIL",
        "Printer remediation verification fails",
        "printer",
        "demo-printer-003",
        "tenant-a",
        "WIN11-PC-005",
        "Printer queue is stuck; remediation will deliberately fail verification for the demo.",
        "restart_spooler",
        ScenarioExpectation.RETRIAGE,
        verification_ok=False,
        expected_injection_block=True,
    ),
    DemoScenario(
        "DEMO-CROSS-TENANT",
        "Cross-tenant incident access denied",
        "printer",
        "demo-printer-tenant-b",
        "tenant-b",
        "WIN11-PC-TB01",
        "Tenant B printer incident must not be visible to tenant A operator.",
        None,
        ScenarioExpectation.DENIED,
        cross_tenant_context=True,
    ),
)
